using System.Text.Json;
using CharacterWizard.Core.Models;

namespace CharacterWizard.Data.Loading;

/// <summary>
/// Reverse index built from 5etools' generated/gendata-spell-source-lookup.json,
/// which maps spell → which classes can cast it. We invert it into
/// (className, classSource) → set&lt;EntityRef&gt; of spells.
///
/// The source file is generated by the 5etools build step; we ship it via the
/// import tool. Without this lookup, the spell file itself does not embed the
/// class list, so filtering "show me only Wizard spells" needs this side table.
/// </summary>
public sealed class ClassSpellListIndex
{
    // Class key is "ClassName|ClassSource" (case-insensitive comparer).
    private readonly Dictionary<string, HashSet<EntityRef>> _byClass = new(StringComparer.OrdinalIgnoreCase);

    public static ClassSpellListIndex LoadFrom(string filePath)
    {
        var idx = new ClassSpellListIndex();
        if (!File.Exists(filePath)) return idx;

        using var stream = File.OpenRead(filePath);
        using var doc = JsonDocument.Parse(stream);

        // shape: { "<spellSourceLower>": { "<spellNameLower>": { "class": { "<classSource>": { "<ClassName>": true } } } } }
        foreach (var spellSourceProp in doc.RootElement.EnumerateObject())
        {
            var spellSource = spellSourceProp.Name.ToUpperInvariant();
            foreach (var spellNameProp in spellSourceProp.Value.EnumerateObject())
            {
                var spellName = spellNameProp.Name; // lowercase; we look up case-insensitively later
                if (!spellNameProp.Value.TryGetProperty("class", out var classBlock) ||
                    classBlock.ValueKind != JsonValueKind.Object) continue;

                foreach (var classSourceProp in classBlock.EnumerateObject())
                {
                    var classSource = classSourceProp.Name;
                    foreach (var classNameProp in classSourceProp.Value.EnumerateObject())
                    {
                        var className = classNameProp.Name;
                        idx.Add(className, classSource, spellName, spellSource);
                    }
                }
            }
        }

        return idx;
    }

    private void Add(string className, string classSource, string spellName, string spellSource)
    {
        var key = className + "|" + classSource;
        if (!_byClass.TryGetValue(key, out var set))
            _byClass[key] = set = new HashSet<EntityRef>();
        set.Add(new EntityRef(spellName, spellSource));
    }

    /// <summary>
    /// Returns true if the given class (by name+source) has access to the given
    /// spell. Names are matched case-insensitively against the lookup which is
    /// already lowercased on the spell side.
    /// </summary>
    public bool ClassHasSpell(string className, string classSource, string spellName, string spellSource)
    {
        var key = className + "|" + classSource;
        if (!_byClass.TryGetValue(key, out var set)) return false;
        // The lookup file stores spell names lowercased — normalize the query.
        return set.Contains(new EntityRef(spellName.ToLowerInvariant(), spellSource));
    }

    public int IndexedClassCount => _byClass.Count;
}
